app-web:
  build: .
  ports:
    - "8080:8080"
  links:
    - app-db

app-db:
  image: postgres:10.12
  ports:
    - "5434:5432"
  environment:
    - DEBUG=true
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root

app-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data