version: '3'

services:

  tomcat-container:
    container_name: tomcat-container
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-container

  postgres-container:
    image: postgres:10.12
    container_name: postgres-container
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=schedule
      - POSTGRES_HOST=postgres-container
    ports:
      - "5432:5432"
    volumes:
      - /usr/local/var/postgres/data




