version: '3'

services:


  postgres-container:
    image: postgres:10.12
    container_name: postgres-container
#    expose:
#      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule
      POSTGRES_HOST: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - /usr/local/var/postgres/data

#  postgres-data:
#      container_name: postgres-data
#      image: busybox
#      command: echo 'Data Container for PostgreSQL'
#      volumes:
#       - /usr/local/var/postgres/data

  tomcat-container:
    container_name: tomcat-container
    build: .
    ports:
      - "8080:8080"
#    links:
#      - postgres-container
    depends_on:
      - postgres-container

