version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    volumes:
      - schedule:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db_network
  class_schedule:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8080:8080
    networks:
      - db_network
volumes:
    schedule: {}
networks:
  db_network:
    driver: bridge