version: '3'

services:
  tomcat-container:
    container_name: tomcat-container
    build: .
    ports:
      - 8080:8080
    links:
      - postgres-container

  postgres-container:
    container_name: postgres-container
    image: postgres:10.12
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:root
      - POSTGRES_DB:schedule
#    ports:
#      - 5432:5432
    volumes:
      - app-db-data



  app-db-data:
      container_name: postgres-data
      image: busybox
      command: echo 'Data Container for PostgreSQL'
      volumes:
       - /usr/local/var/postgres/data

